apiVersion: v1
kind: Pod
metadata:
  name: no-limits-pod
  namespace: limits
  deletionGracePeriodSeconds: 0
spec:
  containers:
    - name: no-limits-container
      image: no-limits:v1
      imagePullPolicy: IfNotPresent

